# Generated by Django 6.0 on 2025-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=150)),
                ('lead_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('lead_phone', models.CharField(max_length=15, unique=True)),
                ('lead_company', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_region', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_address', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
