# Generated by Django 6.0 on 2026-01-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=150)),
                ('lead_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('lead_phone', models.CharField(max_length=15, unique=True)),
                ('lead_company', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_region', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_address', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('second-attempt', 'Second Attempt'), ('third-attempt', 'Third Attempt'), ('completed', 'Completed'), ('followup', 'Follow Up'), ('deal-won', 'Deal Won'), ('deal-lost', 'Deal Lost'), ('dnd', 'Do Not Disturb'), ('prospect', 'Prospect')], default='unassigned', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='Authentication.loginuser')),
            ],
        ),
    ]
