# Generated by Django 6.0 on 2025-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('second-attempt', 'Second Attempt'), ('third-attempt', 'Third Attempt'), ('completed', 'Completed'), ('followup', 'Follow Up'), ('deal-won', 'Deal Won'), ('deal-lost', 'Deal Lost'), ('dnd', 'Do Not Disturb'), ('prospect', 'Prospect')], default='unassigned', max_length=20),
        ),
    ]
